package com.example.model

object AnimeDatabase {
    val allCharacters: List<AnimeCharacter> = listOf(
        AnimeCharacter(
            id = "luffy_g5",
            nameAr = "مونكي دي لوفي (غير 5)",
            nameEn = "LUFFY GEAR 5",
            animeTitleAr = "ون بيس (One Piece)",
            category = AnimeCategory.SHONEN,
            roleAr = "يونكو قراصنة قبعة القش",
            powerRating = 98,
            rarity = CharacterRarity.SSS,
            basePriceM = 30,
            signatureSkillAr = "باجرانغ غن - إيقاظ نيكا",
            clanOrAffiliation = "عائلة الدي / قبعة القش",
            imageUrl = "https://cdn.myanimelist.net/images/characters/9/310307.jpg",
            stats = CharacterStats(attack = 99, speed = 96, iq = 85, special = 99),
            primaryColorHex = 0xFFFFD700,
            secondaryColorHex = 0xFFFF3366,
            quoteAr = "سأكون ملك القراصنة القادم!"
        ),
        AnimeCharacter(
            id = "gojo",
            nameAr = "ساتورو غوجو",
            nameEn = "GOJO SATORU",
            animeTitleAr = "جوجيتسو كايسن (JJK)",
            category = AnimeCategory.MAGIC,
            roleAr = "أقوى مستعمل جوجيتسو",
            powerRating = 97,
            rarity = CharacterRarity.SSS,
            basePriceM = 28,
            signatureSkillAr = "توسيع المجال: الفراغ اللانهائي",
            clanOrAffiliation = "عشيرة غوجو",
            imageUrl = "https://cdn.myanimelist.net/images/characters/15/422168.jpg",
            stats = CharacterStats(attack = 98, speed = 99, iq = 94, special = 99),
            primaryColorHex = 0xFF00E5FF,
            secondaryColorHex = 0xFF4A148C,
            quoteAr = "لا تقلق، أنا الأقوى."
        ),
        AnimeCharacter(
            id = "levi",
            nameAr = "ليفاي أكرمان",
            nameEn = "LEVI ACKERMAN",
            animeTitleAr = "هجوم العمالقة (AOT)",
            category = AnimeCategory.DARK,
            roleAr = "أقوى جندي للبشرية",
            powerRating = 94,
            rarity = CharacterRarity.SS,
            basePriceM = 22,
            signatureSkillAr = "مناورات ثلاثية الأبعاد قاطعة",
            clanOrAffiliation = "فيلق الاستطلاع / عشيرة أكرمان",
            imageUrl = "https://cdn.myanimelist.net/images/characters/2/241417.jpg",
            stats = CharacterStats(attack = 96, speed = 98, iq = 91, special = 90),
            primaryColorHex = 0xFF2E7D32,
            secondaryColorHex = 0xFF263238,
            quoteAr = "اتخذ القرار الذي لن تندم عليه."
        ),
        AnimeCharacter(
            id = "itachi",
            nameAr = "إيتاتشي أوتشيها",
            nameEn = "ITACHI UCHIHA",
            animeTitleAr = "ناروتو شيبودن (Naruto)",
            category = AnimeCategory.SHONEN,
            roleAr = "أسطورة الشارينغان الخفية",
            powerRating = 95,
            rarity = CharacterRarity.SS,
            basePriceM = 25,
            signatureSkillAr = "تسوكيومي وسوسانو سيف توتسوكا",
            clanOrAffiliation = "عشيرة الأوتشيها / الأكاتسكي",
            imageUrl = "https://cdn.myanimelist.net/images/characters/8/131495.jpg",
            stats = CharacterStats(attack = 94, speed = 95, iq = 99, special = 97),
            primaryColorHex = 0xFFFF1744,
            secondaryColorHex = 0xFF212121,
            quoteAr = "كل شخص يعيش في حدود معرفته وإدراكه."
        ),
        AnimeCharacter(
            id = "goku_ui",
            nameAr = "سون غوكو (ألترا إنستنكت)",
            nameEn = "GOKU ULTRA INSTINCT",
            animeTitleAr = "دراغون بول سوبر (DBZ)",
            category = AnimeCategory.SHONEN,
            roleAr = "محارب السايان الأسطوري",
            powerRating = 99,
            rarity = CharacterRarity.SSS,
            basePriceM = 35,
            signatureSkillAr = "الغريزة الفائقة المتقنة",
            clanOrAffiliation = "مقاتلو زد / السايان",
            imageUrl = "https://cdn.myanimelist.net/images/characters/7/284121.jpg",
            stats = CharacterStats(attack = 99, speed = 99, iq = 87, special = 99),
            primaryColorHex = 0xFFECEFF1,
            secondaryColorHex = 0xFF2979FF,
            quoteAr = "جسدي يتحرك تلقائياً لتفادي كل هجوم!"
        ),
        AnimeCharacter(
            id = "madara",
            nameAr = "مادارا أوتشيها",
            nameEn = "MADARA UCHIHA",
            animeTitleAr = "ناروتو شيبودن (Naruto)",
            category = AnimeCategory.SHONEN,
            roleAr = "شبح الأوتشيها وحكيم المسارات",
            powerRating = 97,
            rarity = CharacterRarity.SSS,
            basePriceM = 29,
            signatureSkillAr = "تينغاي شينسي (سقوط النيزك)",
            clanOrAffiliation = "عشيرة الأوتشيها",
            imageUrl = "https://cdn.myanimelist.net/images/characters/8/179373.jpg",
            stats = CharacterStats(attack = 98, speed = 96, iq = 97, special = 98),
            primaryColorHex = 0xFFD50000,
            secondaryColorHex = 0xFF1A237E,
            quoteAr = "استيقظ على الواقع.. في هذا العالم لا يوجد سوى الألم."
        ),
        AnimeCharacter(
            id = "sukuna",
            nameAr = "ريومين سوكونا",
            nameEn = "RYOMEN SUKUNA",
            animeTitleAr = "جوجيتسو كايسن (JJK)",
            category = AnimeCategory.MAGIC,
            roleAr = "ملك اللعنات الذي لا يقهر",
            powerRating = 98,
            rarity = CharacterRarity.SSS,
            basePriceM = 31,
            signatureSkillAr = "توسيع المجال: ضريح الموت الخبيث",
            clanOrAffiliation = "كيان ملعون قديم",
            imageUrl = "https://cdn.myanimelist.net/images/characters/9/426038.jpg",
            stats = CharacterStats(attack = 99, speed = 97, iq = 96, special = 99),
            primaryColorHex = 0xFFB71C1C,
            secondaryColorHex = 0xFF263238,
            quoteAr = "اعرف مكانتك أيها الأحمق."
        ),
        AnimeCharacter(
            id = "zoro",
            nameAr = "رورونوا زورو (ملك الجحيم)",
            nameEn = "RORONOA ZORO",
            animeTitleAr = "ون بيس (One Piece)",
            category = AnimeCategory.SHONEN,
            roleAr = "أعظم سياف قادم وقاطع التنانين",
            powerRating = 93,
            rarity = CharacterRarity.SS,
            basePriceM = 21,
            signatureSkillAr = "أسلوب الثلاث سيوف: ملك الجحيم أورا",
            clanOrAffiliation = "طاقم قبعة القش / وانو",
            imageUrl = "https://cdn.myanimelist.net/images/characters/3/100534.jpg",
            stats = CharacterStats(attack = 96, speed = 93, iq = 84, special = 94),
            primaryColorHex = 0xFF00C853,
            secondaryColorHex = 0xFF1B5E20,
            quoteAr = "الجرح في ظهر السياف عار لا يغتفر!"
        ),
        AnimeCharacter(
            id = "eren",
            nameAr = "إيرين ييغر (العملاق المؤسس)",
            nameEn = "EREN YEAGER",
            animeTitleAr = "هجوم العمالقة (AOT)",
            category = AnimeCategory.DARK,
            roleAr = "محرر الإلديا ومفعل الدك",
            powerRating = 96,
            rarity = CharacterRarity.SSS,
            basePriceM = 27,
            signatureSkillAr = "دك الأرض وملايين العمالقة",
            clanOrAffiliation = "فيلق الاستطلاع / الإلديان",
            imageUrl = "https://cdn.myanimelist.net/images/characters/10/216895.jpg",
            stats = CharacterStats(attack = 98, speed = 88, iq = 92, special = 98),
            primaryColorHex = 0xFFFF6D00,
            secondaryColorHex = 0xFF3E2723,
            quoteAr = "إن لم تقاتل فلن تنتصر، قاتل.. قاتل!"
        ),
        AnimeCharacter(
            id = "saitama",
            nameAr = "سايتاما (رجل اللكمة الواحدة)",
            nameEn = "SAITAMA",
            animeTitleAr = "ون بنش مان (One Punch Man)",
            category = AnimeCategory.MAGIC,
            roleAr = "البطل الخارق بدافع الهواية",
            powerRating = 99,
            rarity = CharacterRarity.SSS,
            basePriceM = 34,
            signatureSkillAr = "السلسلة الجادة: اللكمة الخارقة",
            clanOrAffiliation = "جمعية الأبطال (الفئة B)",
            imageUrl = "https://cdn.myanimelist.net/images/characters/11/294388.jpg",
            stats = CharacterStats(attack = 99, speed = 99, iq = 80, special = 99),
            primaryColorHex = 0xFFFFD600,
            secondaryColorHex = 0xFFD50000,
            quoteAr = "أنا مجرد شخص يمارس البطولة كهواية."
        ),
        AnimeCharacter(
            id = "killua",
            nameAr = "كيلوا زولديك (غودسبيد)",
            nameEn = "KILLUA ZOLDYCK",
            animeTitleAr = "هنتر x هنتر (HxH)",
            category = AnimeCategory.CLASSIC,
            roleAr = "صياد محترف ووريث الاغتيال",
            powerRating = 92,
            rarity = CharacterRarity.SS,
            basePriceM = 19,
            signatureSkillAr = "سرعة الإله (كانمورو)",
            clanOrAffiliation = "عائلة الزولديك",
            imageUrl = "https://cdn.myanimelist.net/images/characters/2/327920.jpg",
            stats = CharacterStats(attack = 92, speed = 99, iq = 95, special = 91),
            primaryColorHex = 0xFF00E5FF,
            secondaryColorHex = 0xFF304FFE,
            quoteAr = "غون، أنت نوري الخاص!"
        ),
        AnimeCharacter(
            id = "light",
            nameAr = "لايت ياغامي (كيرا)",
            nameEn = "LIGHT YAGAMI",
            animeTitleAr = "مذكرة الموت (Death Note)",
            category = AnimeCategory.DARK,
            roleAr = "إله العالم الجديد والعبقري الخارق",
            powerRating = 91,
            rarity = CharacterRarity.SS,
            basePriceM = 18,
            signatureSkillAr = "حكم مذكرة الموت والتلاعب بالعقول",
            clanOrAffiliation = "مذكرة الموت / الشينيغامي ريوك",
            imageUrl = "https://cdn.myanimelist.net/images/characters/6/63870.jpg",
            stats = CharacterStats(attack = 80, speed = 85, iq = 99, special = 97),
            primaryColorHex = 0xFFD50000,
            secondaryColorHex = 0xFF212121,
            quoteAr = "أنا سأصبح إله هذا العالم الجديد!"
        ),
        AnimeCharacter(
            id = "sung_jinwoo",
            nameAr = "سونغ جين وو (ملك الظلال)",
            nameEn = "SUNG JIN-WOO",
            animeTitleAr = "سولو ليفلينغ (Solo Leveling)",
            category = AnimeCategory.MAGIC,
            roleAr = "الصياد الأقوى وحاكم الموتى",
            powerRating = 98,
            rarity = CharacterRarity.SSS,
            basePriceM = 32,
            signatureSkillAr = "انهض (Arise) واستدعاء جيش الظلال",
            clanOrAffiliation = "نقابة أهجين / حكام الظلال",
            imageUrl = "https://cdn.myanimelist.net/images/characters/16/533357.jpg",
            stats = CharacterStats(attack = 99, speed = 98, iq = 93, special = 99),
            primaryColorHex = 0xFF7C4DFF,
            secondaryColorHex = 0xFF12005E,
            quoteAr = "انهض (Arise)."
        ),
        AnimeCharacter(
            id = "whitebeard",
            nameAr = "إدوارد نيوجيت (اللحية البيضاء)",
            nameEn = "WHITEBEARD",
            animeTitleAr = "ون بيس (One Piece)",
            category = AnimeCategory.SHONEN,
            roleAr = "أقوى رجل في العالم سابقاً",
            powerRating = 96,
            rarity = CharacterRarity.SSS,
            basePriceM = 26,
            signatureSkillAr = "فاكهة الزلازل: تدمير المحيط",
            clanOrAffiliation = "قراصنة اللحية البيضاء",
            imageUrl = "https://cdn.myanimelist.net/images/characters/14/110996.jpg",
            stats = CharacterStats(attack = 99, speed = 87, iq = 90, special = 98),
            primaryColorHex = 0xFFFFF176,
            secondaryColorHex = 0xFF880E4F,
            quoteAr = "ون بيس موجود بالفعل!"
        ),
        AnimeCharacter(
            id = "aizen",
            nameAr = "سوسكي آيزن",
            nameEn = "SOSUKE AIZEN",
            animeTitleAr = "بليتش (Bleach)",
            category = AnimeCategory.SHONEN,
            roleAr = "سيد الهويكو موندو والهويغيوكو",
            powerRating = 96,
            rarity = CharacterRarity.SSS,
            basePriceM = 27,
            signatureSkillAr = "كيوكا سويغتسو (التنويم المطلق)",
            clanOrAffiliation = "الإسبادا / مجتمع الأرواح السابق",
            imageUrl = "https://cdn.myanimelist.net/images/characters/3/73212.jpg",
            stats = CharacterStats(attack = 97, speed = 96, iq = 99, special = 98),
            primaryColorHex = 0xFF651FFF,
            secondaryColorHex = 0xFF212121,
            quoteAr = "منذ البداية، لم يقف أحد في السماء قبلي."
        ),
        AnimeCharacter(
            id = "ichigo",
            nameAr = "إيتشيغو كوروساكي (هورن أوف سالفيشن)",
            nameEn = "ICHIGO KUROSAKI",
            animeTitleAr = "بليتش (Bleach)",
            category = AnimeCategory.SHONEN,
            roleAr = "الشينيغامي البديل وهجين القوى",
            powerRating = 95,
            rarity = CharacterRarity.SS,
            basePriceM = 24,
            signatureSkillAr = "غيتسوغا تينشو النهائية",
            clanOrAffiliation = "الشينيغامي البديل / عشيرة شيبا",
            imageUrl = "https://cdn.myanimelist.net/images/characters/3/54898.jpg",
            stats = CharacterStats(attack = 97, speed = 97, iq = 87, special = 96),
            primaryColorHex = 0xFFFF6D00,
            secondaryColorHex = 0xFF212121,
            quoteAr = "إذا تغير القدر، سأحطمه بسيفي!"
        ),
        AnimeCharacter(
            id = "shanks",
            nameAr = "شانكس ذو الشعر الأحمر",
            nameEn = "RED-HAIRED SHANKS",
            animeTitleAr = "ون بيس (One Piece)",
            category = AnimeCategory.SHONEN,
            roleAr = "يونكو البحر وصاحب أقوى هاكي",
            powerRating = 97,
            rarity = CharacterRarity.SSS,
            basePriceM = 30,
            signatureSkillAr = "كاموساري (المغادرة الإلهية)",
            clanOrAffiliation = "قراصنة الشعر الأحمر",
            imageUrl = "https://cdn.myanimelist.net/images/characters/12/310306.jpg",
            stats = CharacterStats(attack = 98, speed = 96, iq = 95, special = 99),
            primaryColorHex = 0xFFD50000,
            secondaryColorHex = 0xFF3E2723,
            quoteAr = "لقد جئت لإنهاء هذه الحرب!"
        ),
        AnimeCharacter(
            id = "guts",
            nameAr = "غاتس (السياف الأسود)",
            nameEn = "GUTS THE BLACK SWORDSMAN",
            animeTitleAr = "بيرسيرك (Berserk)",
            category = AnimeCategory.DARK,
            roleAr = "المحارب المتحدي للمصير والإله",
            powerRating = 93,
            rarity = CharacterRarity.SS,
            basePriceM = 20,
            signatureSkillAr = "درع البيرسيركر وسيف دراغونسلاير",
            clanOrAffiliation = "فرقة الصقر السابقة",
            imageUrl = "https://cdn.myanimelist.net/images/characters/15/73235.jpg",
            stats = CharacterStats(attack = 97, speed = 90, iq = 88, special = 94),
            primaryColorHex = 0xFF424242,
            secondaryColorHex = 0xFFB71C1C,
            quoteAr = "إذا كنت سأصل لشيء، فلن يكون بالركوع لأحد."
        ),
        AnimeCharacter(
            id = "meruem",
            nameAr = "ميريوم (ملك نمل الكيميرا)",
            nameEn = "KING MERUEM",
            animeTitleAr = "هنتر x هنتر (HxH)",
            category = AnimeCategory.CLASSIC,
            roleAr = "قمة التطور والذكاء الطبيعي",
            powerRating = 97,
            rarity = CharacterRarity.SSS,
            basePriceM = 29,
            signatureSkillAr = "فوتون النين وقوة الهالة التي لا تحد",
            clanOrAffiliation = "نمل الكيميرا الملكي",
            imageUrl = "https://cdn.myanimelist.net/images/characters/12/252981.jpg",
            stats = CharacterStats(attack = 99, speed = 98, iq = 98, special = 97),
            primaryColorHex = 0xFF00E676,
            secondaryColorHex = 0xFF4A148C,
            quoteAr = "كنت أظن القوة كل شيء، حتى التقيت بكِ يا كوموغي."
        ),
        AnimeCharacter(
            id = "rengoku",
            nameAr = "كوجورو رينغوكو (هاشيرا اللهب)",
            nameEn = "RENGOKU KYOJURO",
            animeTitleAr = "قاتل الشياطين (Demon Slayer)",
            category = AnimeCategory.MAGIC,
            roleAr = "هاشيرا اللهب الشجاع",
            powerRating = 90,
            rarity = CharacterRarity.S,
            basePriceM = 16,
            signatureSkillAr = "تنفس اللهب: النموذج التاسع رينغوكو",
            clanOrAffiliation = "فيلق قتلة الشياطين",
            imageUrl = "https://cdn.myanimelist.net/images/characters/11/427632.jpg",
            stats = CharacterStats(attack = 93, speed = 92, iq = 86, special = 89),
            primaryColorHex = 0xFFFF5722,
            secondaryColorHex = 0xFFFFEB3B,
            quoteAr = "أشعل لهيب قلبك وتجاوز حدودك!"
        ),
        AnimeCharacter(
            id = "l_lawliet",
            nameAr = "إل لولايت (L)",
            nameEn = "L LAWLIET",
            animeTitleAr = "مذكرة الموت (Death Note)",
            category = AnimeCategory.DARK,
            roleAr = "أعظم محقق في تاريخ البشرية",
            powerRating = 92,
            rarity = CharacterRarity.SS,
            basePriceM = 19,
            signatureSkillAr = "استنتاج خارق وسرعة بديهة مطلقة",
            clanOrAffiliation = "منظمة التحقيق العالمية",
            imageUrl = "https://cdn.myanimelist.net/images/characters/10/59983.jpg",
            stats = CharacterStats(attack = 75, speed = 84, iq = 99, special = 95),
            primaryColorHex = 0xFF607D8B,
            secondaryColorHex = 0xFF212121,
            quoteAr = "كيرا.. سأمسك بك حتى لو كلفني ذلك حياتي."
        ),
        AnimeCharacter(
            id = "minato",
            nameAr = "ميناتو ناميكازي",
            nameEn = "MINATO NAMIKAZE",
            animeTitleAr = "ناروتو شيبودن (Naruto)",
            category = AnimeCategory.SHONEN,
            roleAr = "الهوكاجي الرابع ووميض كونوها",
            powerRating = 94,
            rarity = CharacterRarity.SS,
            basePriceM = 23,
            signatureSkillAr = "الراسينغان وتقنية إله الرعد الطائر",
            clanOrAffiliation = "قرية كونوها",
            imageUrl = "https://cdn.myanimelist.net/images/characters/7/284499.jpg",
            stats = CharacterStats(attack = 94, speed = 99, iq = 96, special = 94),
            primaryColorHex = 0xFFFFD700,
            secondaryColorHex = 0xFF0D47A1,
            quoteAr = "أنا أسرع شينوبي في العالم."
        ),
        AnimeCharacter(
            id = "law",
            nameAr = "ترافالغار لاو (جراح الموت)",
            nameEn = "TRAFALGAR D. WATER LAW",
            animeTitleAr = "ون بيس (One Piece)",
            category = AnimeCategory.SHONEN,
            roleAr = "جراح الموت وقائد قراصنة القلب",
            powerRating = 92,
            rarity = CharacterRarity.SS,
            basePriceM = 20,
            signatureSkillAr = "إيقاظ الغرفة (ROOM: K-ROOM)",
            clanOrAffiliation = "عائلة الدي / قراصنة القلب",
            imageUrl = "https://cdn.myanimelist.net/images/characters/4/110997.jpg",
            stats = CharacterStats(attack = 92, speed = 91, iq = 96, special = 95),
            primaryColorHex = 0xFF00B0FF,
            secondaryColorHex = 0xFF212121,
            quoteAr = "الضعفاء لا يملكون الحق في اختيار طريقة موتهم."
        ),
        AnimeCharacter(
            id = "toji",
            nameAr = "توجي فوشيغورو (قاتل السحرة)",
            nameEn = "TOJI FUSHIGURO",
            animeTitleAr = "جوجيتسو كايسن (JJK)",
            category = AnimeCategory.MAGIC,
            roleAr = "المحارب ذو التقييد السماوي الخارق",
            powerRating = 92,
            rarity = CharacterRarity.SS,
            basePriceM = 19,
            signatureSkillAr = "رمح السماء المقلوب وقوة الجسد الصرف",
            clanOrAffiliation = "عشيرة الزينين السابقة",
            imageUrl = "https://cdn.myanimelist.net/images/characters/8/516086.jpg",
            stats = CharacterStats(attack = 96, speed = 97, iq = 92, special = 89),
            primaryColorHex = 0xFF546E7A,
            secondaryColorHex = 0xFF212121,
            quoteAr = "هل سيموت سحرة الجوجيتسو أمام رجل بلا طاقة ملعونة؟"
        ),
        AnimeCharacter(
            id = "kaneki",
            nameAr = "كين كانيكي (الغول ذو العين الواحدة)",
            nameEn = "KEN KANEKI",
            animeTitleAr = "طوكيو غول (Tokyo Ghoul)",
            category = AnimeCategory.DARK,
            roleAr = "ملك الغيلان ذو العين الواحدة",
            powerRating = 89,
            rarity = CharacterRarity.S,
            basePriceM = 15,
            signatureSkillAr = "الكاغو السنتيبيد ومخالب الريميكس",
            clanOrAffiliation = "منظمة الأنتيك / الغيلان",
            imageUrl = "https://cdn.myanimelist.net/images/characters/9/253811.jpg",
            stats = CharacterStats(attack = 91, speed = 92, iq = 89, special = 89),
            primaryColorHex = 0xFFE91E63,
            secondaryColorHex = 0xFF212121,
            quoteAr = "كم يساوي 1000 ناقص 7؟"
        ),
        AnimeCharacter(
            id = "erwin",
            nameAr = "إروين سميث (القائد الحكيم)",
            nameEn = "ERWIN SMITH",
            animeTitleAr = "هجوم العمالقة (AOT)",
            category = AnimeCategory.DARK,
            roleAr = "القائد الثالث عشر لفيلق الاستطلاع",
            powerRating = 91,
            rarity = CharacterRarity.SS,
            basePriceM = 17,
            signatureSkillAr = "هتاف الشجاعة والخطط التكتيكية الحاسمة",
            clanOrAffiliation = "فيلق الاستطلاع",
            imageUrl = "https://cdn.myanimelist.net/images/characters/3/260783.jpg",
            stats = CharacterStats(attack = 88, speed = 87, iq = 99, special = 93),
            primaryColorHex = 0xFFFBC02D,
            secondaryColorHex = 0xFF1B5E20,
            quoteAr = "جنودي يصرخون! جنودي يقاتلون! جنودي يضحون بأنفسهم!"
        ),
        AnimeCharacter(
            id = "netero",
            nameAr = "إسحاق نيتيرو (رئيس جمعية الصيادين)",
            nameEn = "ISAAC NETERO",
            animeTitleAr = "هنتر x هنتر (HxH)",
            category = AnimeCategory.CLASSIC,
            roleAr = "رئيس الصيادين وأقوى مستعمل نين",
            powerRating = 95,
            rarity = CharacterRarity.SS,
            basePriceM = 25,
            signatureSkillAr = "بوديساتف غوانيين ذات الأيدي المئة",
            clanOrAffiliation = "جمعية الصيادين المحترفين",
            imageUrl = "https://cdn.myanimelist.net/images/characters/12/252985.jpg",
            stats = CharacterStats(attack = 97, speed = 99, iq = 94, special = 97),
            primaryColorHex = 0xFFFFB300,
            secondaryColorHex = 0xFF37474F,
            quoteAr = "لقد قضيت سنوات أشكر الفنون القتالية حتى فاقت سرعتي الصوت."
        ),
        AnimeCharacter(
            id = "buggy",
            nameAr = "المهرج باغي (يونكو بالحظ)",
            nameEn = "BUGGY THE CLOWN",
            animeTitleAr = "ون بيس (One Piece)",
            category = AnimeCategory.SHONEN,
            roleAr = "يونكو بالصدفة وقائد كروس غيلد",
            powerRating = 69,
            rarity = CharacterRarity.TROLL,
            basePriceM = 8,
            signatureSkillAr = "فاكهة التقطيع وحظ أسطوري غير مبرر",
            clanOrAffiliation = "كروس غيلد / قراصنة روجر السابقين",
            imageUrl = "https://cdn.myanimelist.net/images/characters/14/310305.jpg",
            stats = CharacterStats(attack = 65, speed = 70, iq = 75, special = 99),
            primaryColorHex = 0xFFE91E63,
            secondaryColorHex = 0xFF00E5FF,
            quoteAr = "كيف أصبحت يونكو؟ حتى أنا لا أعلم!"
        ),
        AnimeCharacter(
            id = "yamcha",
            nameAr = "يامتشا (أسطورة الهزائم)",
            nameEn = "YAMCHA",
            animeTitleAr = "دراغون بول (Dragon Ball)",
            category = AnimeCategory.CLASSIC,
            roleAr = "مقاتل زد وصاحب وضعية السقوط الشهيرة",
            powerRating = 64,
            rarity = CharacterRarity.TROLL,
            basePriceM = 5,
            signatureSkillAr = "قبضة ذئب الصحراء والسقوط الفوري",
            clanOrAffiliation = "مقاتلو زد الأرضيون",
            imageUrl = "https://cdn.myanimelist.net/images/characters/4/71618.jpg",
            stats = CharacterStats(attack = 68, speed = 72, iq = 60, special = 55),
            primaryColorHex = 0xFFFF9800,
            secondaryColorHex = 0xFF455A64,
            quoteAr = "سأفعل ما بوسعي.. أتمنى ألا ينفجر سايبامان!"
        )
    )

    fun getCharactersForPool(category: AnimeCategory): List<AnimeCharacter> {
        return if (category == AnimeCategory.ALL) {
            allCharacters
        } else {
            allCharacters.filter { it.category == category || it.rarity == CharacterRarity.SSS }
        }
    }
}
